version: '3'

services:
  graphql-explorer:
    container_name: graphql-explorer
    build:
      context: .
      args:
        - NPM_TOKEN=${NPM_TOKEN}
    restart: unless-stopped
    ports: 
      - '9506:3000'
    environment:
      - SERVER_URL=http://localhost/v1/graphql